language: python
python:
  - "3.5"
  - "3.6"
# Command to install dependencies
install:
  - pip install -U pip setuptools
  - pip install -U mypy==0.560  # v0.570 has a bug https://github.com/python/mypy/issues/4674 ; use 0.560 for now
  - pip install -U flake8
  - pip install -r requirements.txt
# Command to run tests
script:
  - python -m flake8 sslyze
  - python -m mypy sslyze
  - python run_tests.py
